# Generated by Django 5.0.2 on 2024-03-12 11:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'категории рецептов',
                'verbose_name_plural': 'Категории рецептов',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название рецепта')),
                ('description', models.TextField(default='', max_length=4000, verbose_name='Описание рецепта')),
                ('cooking_steps', models.TextField(default='', verbose_name='Последовательность приготовления')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Ингредиенты')),
                ('cooking_time_in_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos_cooked_recipes/', verbose_name='Изображение блюда')),
                ('publicated_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('chaged_date', models.DateField(auto_now=True, verbose_name='Дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('category', models.ManyToManyField(to='recipe_site_app.recipecategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='CommentsOnRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=3000, verbose_name='Комментарий')),
                ('publicated_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('chaged_date', models.DateField(auto_now=True, verbose_name='Автор')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_site_app.recipes', verbose_name=' Рецепт')),
            ],
            options={
                'verbose_name': 'комментарии к рецептам',
                'verbose_name_plural': 'Комментарии к рецептам',
            },
        ),
    ]
